version: '3.8'

services:
  threatresearchhub:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///app/data/threatresearchhub.db
    restart: unless-stopped
    
  # Optional: PostgreSQL database for production use
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: threatresearchhub
      POSTGRES_USER: threat_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: