id: 83fb3958-8233-4feb-8efc-1da2bf3ee97e
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: NE - Malware Response Playbook Core
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0d98dd0d-1d62-4439-8e5d-4aa52542106f
    type: start
    task:
      id: 0d98dd0d-1d62-4439-8e5d-4aa52542106f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 08bdecb4-ef3c-4232-83cf-da5081e81dbd
    type: condition
    task:
      id: 08bdecb4-ef3c-4232-83cf-da5081e81dbd
      version: -1
      name: Was the alert prevented?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.action
            iscontext: true
          right:
            value:
              simple: PREVENTED
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1657.5,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 0561af4c-5d84-4455-8f54-c51829d6bea9
    type: regular
    task:
      id: 0561af4c-5d84-4455-8f54-c51829d6bea9
      version: -1
      name: Close Alert
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1985,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c3091ed3-dd17-4611-86f5-7d92e796a9b0
    type: condition
    task:
      id: c3091ed3-dd17-4611-86f5-7d92e796a9b0
      version: -1
      name: Were there any confirmed malicious or suspicious indicators?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
          right:
            value:
              simple: "1"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 0934ee9d-f83f-47f7-826a-34a76b3951e4
    type: regular
    task:
      id: 0934ee9d-f83f-47f7-826a-34a76b3951e4
      version: -1
      name: Increase alert severity to High
      description: Optionally increases the incident severity to the new value if
        it is greater than the existing severity.
      scriptName: IncreaseIncidentSeverity
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      severity:
        simple: High
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1882.5,
          "y": 1275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: fbdb2e89-7571-464c-8942-5976def03655
    type: regular
    task:
      id: fbdb2e89-7571-464c-8942-5976def03655
      version: -1
      name: Isolate Endpoint
      description: Isolates the specified endpoint.
      script: '|||core-isolate-endpoint'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      endpoint_id:
        simple: ${alert.agentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1882.5,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a6ec967f-df8c-41b2-87a4-2c93857deca6
    type: regular
    task:
      id: a6ec967f-df8c-41b2-87a4-2c93857deca6
      version: -1
      name: Manual Review
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1882.5,
          "y": 1625
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: bca87f36-3766-4e23-8453-171815868f35
    type: regular
    task:
      id: bca87f36-3766-4e23-8453-171815868f35
      version: -1
      name: Close Alert
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1882.5,
          "y": 1975
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 8c719444-6906-47ff-89dc-87b9b6f2222e
    type: regular
    task:
      id: 8c719444-6906-47ff-89dc-87b9b6f2222e
      version: -1
      name: Assign Analyst to Incident
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      username:
        simple: nericksen@paloaltonetworks.com
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: ba43e94a-16d3-4693-89da-96493615f479
    type: collection
    task:
      id: ba43e94a-16d3-4693-89da-96493615f479
      version: -1
      name: Send Email Notification to Analyst
      description: Send an email
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      body:
        simple: "${alert.details} \n\n<url link to alert>"
      subject:
        simple: ${alert.name} needs your attention
      to:
        simple: nericksen@paloaltonetworks.com
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: nericksen@paloaltonetworks.com
      subject:
        simple: ${alert.name} needs your attention
      body:
        simple: ${alert.details}
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Should the host be isolated?
        required: false
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: IsolateSurvey
      description: Should the host be isolated?
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: f4700347-eca9-412a-8da7-dcf249a61b4b
    type: regular
    task:
      id: f4700347-eca9-412a-8da7-dcf249a61b4b
      version: -1
      name: Close Alert
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1975
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 4ddf9c6b-0a2c-49cd-822a-ed793fc7b957
    type: regular
    task:
      id: 4ddf9c6b-0a2c-49cd-822a-ed793fc7b957
      version: -1
      name: Isolate Endpoint
      description: Isolates the specified endpoint.
      script: '|||core-isolate-endpoint'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      endpoint_id:
        simple: ${alert.agentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1452.5,
          "y": 1800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 04fcf976-1b32-4447-8613-3b5384868340
    type: condition
    task:
      id: 04fcf976-1b32-4447-8613-3b5384868340
      version: -1
      name: Isolate host?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: IsolateSurvey.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1625
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: aa2ee1f0-c32b-4aaa-82f5-a521307db6a9
    type: regular
    task:
      id: aa2ee1f0-c32b-4aaa-82f5-a521307db6a9
      version: -1
      name: Get file quarantine status
      description: Retrieves the quarantine status for a selected file.
      script: '|||core-get-quarantine-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      endpoint_id:
        complex:
          root: alert
          accessor: agentid
      file_hash:
        complex:
          root: alert
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: alert.initiatorpath
                iscontext: true
              right:
                value:
                  simple: c:\windows\explorer.exe
              ignorecase: true
          accessor: initiatorsha256
          transformers:
          - operator: SetIfEmpty
            args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: alert.targetprocesssha256
                iscontext: true
      file_path:
        complex:
          root: alert.initiatorpath
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: alert.initiatorpath
                iscontext: true
              right:
                value:
                  simple: c:\windows\explorer.exe
              ignorecase: true
          transformers:
          - operator: SetIfEmpty
            args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: alert.targetprocesscmd
                iscontext: true
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: \"
              replaceWith: {}
          - operator: uniq
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: bfa3acd4-f0e5-42a8-8553-55f39449252d
    type: condition
    task:
      id: bfa3acd4-f0e5-42a8-8553-55f39449252d
      version: -1
      name: Was file quarantined?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Core.quarantineFiles.status.status
            iscontext: true
          right:
            value:
              simple: "true"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 925
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: dd920f5b-38bb-48c5-8d67-f2c4ce036de4
    type: regular
    task:
      id: dd920f5b-38bb-48c5-8d67-f2c4ce036de4
      version: -1
      name: Check for Previous Alerts for Same Host and Initiator SHA256 - Last 10
        min
      description: |-
        Searches Demisto alerts. A summarized version of this scrips is avilable with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: SearchAlertsV2
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      query:
        simple: agent.id:${alert.agentid} initiatorsha256:${alert.initiatorsha256}
      sort:
        simple: id.asc
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 1155c502-79ba-4ac9-8172-5498134a1cd7
    type: condition
    task:
      id: 1155c502-79ba-4ac9-8172-5498134a1cd7
      version: -1
      name: Recent Duplicate Alert Found?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: lessThan
          left:
            value:
              complex:
                root: foundIncidents
                transformers:
                - operator: ConvertToSingleElementArray
                - operator: atIndex
                  args:
                    index:
                      value:
                        simple: "0"
                - operator: getField
                  args:
                    field:
                      value:
                        simple: id
            iscontext: true
          right:
            value:
              simple: ${alert.id}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "1_19_yes": 0.87
    },
    "paper": {
      "dimensions": {
        "height": 2005,
        "width": 1025,
        "x": 1340,
        "y": 65
      }
    }
  }
inputs: []
outputs: []
quiet: true
