id: efa047ad-55d7-4414-821b-0b6cca0b369b
version: 11
vcShouldKeepItemLegacyProdMachine: false
name: SE Summit - IOC handling Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: aca61b40-99bf-4655-8677-f9bc20a28e49
    type: start
    task:
      id: aca61b40-99bf-4655-8677-f9bc20a28e49
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 83357a1a-8663-478b-87f6-9bb2bbd1a2c7
    type: regular
    task:
      id: 83357a1a-8663-478b-87f6-9bb2bbd1a2c7
      version: -1
      name: Check Process Prevalence
      description: Get the prevalence of a process, identified by process_name.
      script: '|||core-get-process-analytics-prevalence'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      process_name:
        simple: ${alert.cgoname.[0]}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b559192a-9aa3-4211-818c-d4c7dbc216a3
    type: condition
    task:
      id: b559192a-9aa3-4211-818c-d4c7dbc216a3
      version: -1
      name: Source Process in Known Browsers list?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: alert.cgoname.[0]
            iscontext: true
          right:
            value:
              complex:
                root: lists
                accessor: KnownBrowsers
                transformers:
                - operator: splitAndTrim
                  args:
                    delimiter:
                      value:
                        simple: ','
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: c7f55391-8a4e-4026-807b-cabb63bb8712
    type: regular
    task:
      id: c7f55391-8a4e-4026-807b-cabb63bb8712
      version: -1
      name: Close as FP
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      closeReason:
        simple: Resolved - False Positive
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers:
    - fieldname: detectionsla
      action: stop
    - fieldname: remediationsla
      action: start
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: ca10e09b-d36e-4c1b-8c46-fba46cf3eeb8
    type: condition
    task:
      id: ca10e09b-d36e-4c1b-8c46-fba46cf3eeb8
      version: -1
      name: Global Process Prevalence is over 50%
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              simple: Core.AnalyticsPrevalence.Process.data.global_prevalence.value
            iscontext: true
          right:
            value:
              simple: "0.5"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 8b3b0d3c-a32f-4f22-87d0-7a9bbdbc678f
    type: title
    task:
      id: 8b3b0d3c-a32f-4f22-87d0-7a9bbdbc678f
      version: -1
      name: Detection
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers:
    - fieldname: detectionsla
      action: start
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 7d624b15-66ed-47ae-88f4-a396bdf55120
    type: title
    task:
      id: 7d624b15-66ed-47ae-88f4-a396bdf55120
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1040
        }
      }
    note: false
    timertriggers:
    - fieldname: remediationsla
      action: stop
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
